name             'mysql_config'
maintainer       'Gannett'
maintainer_email 'glane@gannett.com'
license          'All rights reserved'
description      'Installs/Configures mysql_config'
long_description 'Installs/Configures mysql_config'
version          '0.1.0'

depends 'mysql'
depends 'lvm'
depends 'selinux'
depends 'sysctl'
depends 'limits'
depends 'iptables'
depends 'mysql2_chef_gem'
depends 'database'
depends 'gdp-base-linux'
